### PR TITLE
Unbind undef on exports

### PR DESCRIPTION
**Pull request by karleberts**
So I evidently didn't notice that 'exports' was being redefined at the bottom of the file when 'window' existed. oops

Moving the unbind definition to after that point makes it be properly exported.

### CODE REVIEW

**Comment by karleberts** [comment]
For #12

**Comment by KyleAMathews** [comment]
Looks great! Could you resolve the merge conflict? I'll then merge and make a new release.

**Comment by plgregoire** [comment]
Hi, I just tested the modified code and it works. Unbind is now accessible and I'm able to import the lib using ES6 syntax.

However, Using Chrome Developer Tools - Profiles ,I noticed a memory leak when you attach then detach a listener.

**Comment by karleberts** [comment]
thanks @plgregoire, I think this should be ok now?

**Comment by plgregoire** [comment]
Indeed it is !
Thank you

**Comment by plgregoire** [comment]
Hi @KyleAMathews,

When can we expect a release ?

Thanks

**Comment by dapids** [comment]
Hi @KyleAMathews, any news on this?

**Comment by KyleAMathews** [comment]
Published 2.0.8 — thanks for everyone's help!

**Pull request merged**
