### PR TITLE
Add unbind method for removing the listener.

### PR DESCRIPTION
**Pull request by karleberts**
For issue #2 . Added an unbind method to the exported api (pulled the code from the same blog post as the original method).

It might be better to export 2 distinct bind/unbind methods instead of hanging unbind off of the 'default' export. It would require a version bump, but would be an easy change to make.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looks good!

**Comment by codering** [comment]
How to use in es6 ??
```js
import elementResizeEvent, {unbind} from 'element-resize-event'
```

`unbind` is undefined

**Comment by KyleAMathews** [comment]
@codering what's `console.log(elementResizeEvent)` return? Also this should be a new issue. Could you create this as a new issue please and tag @karleberts?

**Comment by plgregoire** [comment]
Does someone have an example on how to access the unbind method ?

**Pull request merged**
